name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Executa nas mudanças da branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao:${{ secrets.CHAVE_SSH_SERVER }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao:${{ secrets.CHAVE_SSH_SERVER }}

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.CHAVE_SSH_SERVER }}
          port: 22
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao:${{ secrets.CHAVE_SSH_SERVER }}
            docker stop minha-aplicacao || true
            docker rm minha-aplicacao || true
            docker run -d -p 8092:3000 --name minha-aplicacao ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao:${{ secrets.CHAVE_SSH_SERVER }}
